name: Deploy para Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto React (CI desativado)
        run: CI='' npm run build

      - name: Verificar conteúdo da build
        run: ls -la ./build

      - name: Deploy via FTP para Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          server-dir: public_html/